# Generated by Django 5.2.12 on 2026-03-30 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('teamname', models.CharField(max_length=50)),
                ('salary', models.FloatField()),
                ('reporteecount', models.IntegerField(default=0)),
            ],
        ),
    ]
